name: MLOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  test-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run pytest
        run: |
          python src/train.py  # Make sure model exists before testing
          pytest

  train-and-quantize:
    runs-on: ubuntu-latest
    needs: test-model
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Train and quantize model
        run: |
          python src/train.py
          python src/quantize.py

  build-and-run:
    runs-on: ubuntu-latest
    needs: train-and-quantize
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and run container
        run: |
          docker build -t mlops-predict .
          docker run mlops-predict
